params:
  epochs: 1
  batchsize: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000




artifacts: 
  artifacts_dir: artifacts_dir
  model_dir: model
  plots_dr: plots
  checkpoint_dr: checkpoints
  model_name: model.h5

logs:
  logs_dir: logs_dr
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs

